############### MISCELLANEOUS ###############

#Pervents player from opening a bases' chest if bases team is still alive
Lock-Team-Chest: false
Team-Chest-Distance: 8
Prevent-Chest-Open-Message: '&cYou cannot open this chest until {team} &chas been eliminated.'

#Change default team chat colors
#Add teams like: "DefaultTeamName:ChatColorCar"
Custom-Team-Chat-Color:
  Enabled: false
  Teams:
    - 'CYAN:3'

#Personal Ender Chests
Personal-Ender-Chests: false

#If enabled you still join a server even if the Player Limit is reached.
Bypass-PlayerLimit: false

#Removes invis on specified damage causes
Break-Invis:
  Enabled: true
  Causes:
    - 'ENTITY_ATTACK'
    - 'BLOCK_EXPLOSION'
    - 'ENTITY_EXPLOSION'

#ArenaName:PotionEffectName:amplifier
#Default amplifier is 1
#All arenas = ALL-ARENAS
Permanent-Effects:
  - 'Ruins:NIGHT_VISION'

#Sponge partials on place
Sponge-Partials: true