############### PREVENT WATER BUILDUP ###############

#Prevents liquids from going outside BW arena
#Will not affect other gamemodes
Prevent-Liquid-Build-Up: true

############### ACTION BAR ###############

#You may want to DISABLE MBedwars's team name actionbar in the config.cm2
Action-Bar-Enabled: false

#Action-Bar-Enabled must be true
Action-Bar-Enabled-In-Lobby: true
Action-Bar-Enabled-In-Game: true

#Supports PAPI Placeholders
Action-Bar-Message: "%tweaks_next-tier%"

############### FINAL KILL ###############

#Adds FINAL KILL to the end of a message if the kill is final
#WARNING: May cause an error. We are looking into a fix, please report any errors in our discord
Final-Kill-Message: true

#Players get a lightning blot at their location of death if it is a final kill
Final-Kill-Strike:
  Enabled: false

############### FIREBALL BLOCK WHITELIST ###############

#Blocks that fireballs will not destroy (Overrides MBedwars' BlackList)
FireballWhitelist:
  Enabled: true
  Blocks:
    - ENDER_STONE
    - END_STONE

############### DISABLE EMPTY BASE GENERATORS ###############

#Disable generators in empty bases
#Range = distance from team spawn to spawner
Disable-Unused-Gens:
  Enabled: false
  Range: 6
  Gen-Types:
    - 'IRON_INGOT'
    - 'GOLD_INGOT'

############### GEN TIERS [BETA] ###############

#Teirs can be configured in the gen-tiers.yml
Gen-Tiers-Enabled: false

#Override MBedwars Holo's
Gen-Tiers-Holos-Enabled: true

#Adds 'Tier I' to spawners listed
Tier-One-Titles:
  Tier-Name: '&eTier &cI'
  Spawners:
    - 'EMERALD'
    - 'DIAMOND'

#Message shown above spawners
# {spawner} {spawner-color} {time} {tier}
Spawner-Title:
  - '{tier}'
  - '{spawner-color}{spawner}'
  - '&eSpawning in &c{time} &eseconds!'

############### BED BREAK ###############

#Message displayed when any bed is broken (to everyone in the arena)
Player-Destroy-Message:
  - ''
  - '&f&lBED DESTRUCTION > {team-color}{team-name} Bed &7was destroyed by {destroyer-color}{destroyer-name}'
  - ''

#Chat message displayed on Auto-Bed-Break
Auto-Destroy-Message:
  - ''
  - '&c&lALL BEDS HAVE BEEN DESTROYED'
  - ''

# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
Bed-Destroy-Sound: 'ENTITY_ENDER_DRAGON_GROWL'

#Title displayed to a player when his bed gets destroyed
#This replaces MBedwars' message, and only gets sent to the player with no bed
Notification:
  Big-Title: '&cBED DESTROYED'
  Small-Title: '&fYou will no longer respawn!'

############### TEAM ELIMINATE ###############

#Message displayed when any team is eliminated (to everyone in the arena)
Team-Eliminate-Message-Enabled: true

#Placeholders: {team-color} {team-name}
Team-Eliminate-Message:
  - ''
  - '&f&lTEAM ELIMINATED > {team-color}{team-name} Team &chas been eliminated!'
  - ''

############### TOP KILLER MESSAGE [BETA] ###############

#Displayed at the end of a game to congratulate yop killers
Top-Killer-Message-Enabled: true

#Displayed if there are no top killers
No-Top-Killers-Message:
  - ''

# PLACEHOLDERS:
# %Killer-1-Name% %Killer-2-Name% %Killer-3-Name%
# %Killer-1-Amount% %Killer-2-Amount% %Killer-3-Amount%
Top-Killer-Message:
  - '&a&l-------------------------------'
  - '                &lBedWars'
  - ''
  - '    &e&l1st Killer &7- %Killer-1-Name% - %Killer-1-Amount%'
  - '    &6&l2nd Killer &7- %Killer-2-Name% - %Killer-2-Amount%'
  - '    &c&l3rd Killer &7- %Killer-3-Name% - %Killer-3-Amount%'
  - ''
  - '&a&l-------------------------------'


############### PAPI PLACEHOLDERS ###############

#PAPI Placeholder: %tweaks_next-tier%
# {next-tier} {time} {sec} {min}
Next-Tier-PAPI-Placeholder:
  Lobby-Waiting: "&fWaiting..."
  Lobby-Starting: "&fStarting in &a{time}s"
  Running: '{next-tier} in &a{time}'
  End-Lobby: '&rGame Over'
  Resetting: '&rArena Regenerating'
  Stopped: '&rArena Stopped'

#PAPI Placeholder: %tweaks_arena-mode%
PAPI-Mode-Placeholder:
  #TeamNumber:PlayerNumber:ModeName
  - '8:2:Duos'
  - '8:1:Solos'
  - '4:3:Trios'
  - '4:4:Quads'

#Whether to count Spectators for the Player Count Placeholders
Player-Count-Placeholder-Count-Spectators: true

#PAPI Placeholder: %tweaks_team-status-{name}%
#To be used on the scoreboard as is above
Team-Status-Placeholder:
  Your-Team: " &7You"
  Has-Bed: "&a✔"
  No-Bed: "&a{player-amount}"
  Team-Dead: "&c✘"

#If set to true, the scoreboard will be force updated to refresh PAPI placeholders
#WARNING: Force updating the MBedwars scoreboard may cause scoreboard flicker
Scoreboard-Updating: false

#Scoreboard will update every X amount of seconds
#Recommended keeping at 5 or 10 seconds
Scoreboard-Updating-Interval: 10

############### HEIGHT CAP ###############

#Add a height cap for specific MBedwars arenas
#Add height cap like 'arenaName:70'
#To disable the message, set to ''
Height-Cap:
  Enabled: false
  Message: '&cYou cannot build any higher'
  Arenas:
    - ''

############### MISCELLANEOUS ###############

#Pervents player from opening a bases' chest if bases team is still alive
Lock-Team-Chest: false
Team-Chest-Distance: 8
Prevent-Chest-Open-Message: '&cYou cannot open this chest until {team} &chas been eliminated.'

#Personal Ender Chests
Personal-Ender-Chests: false

#If enabled you still join a server even if the Player Limit is reached.
Bypass-PlayerLimit: false

#Shortens lobby time to a specified value
#if arena filled over a certain percent
Shorten-Countdown:
  Enabled: false
  Minimum-Percent-Filled: 80
  Shorten-Time-To: 10

#Removes invis on specified damage causes
#I recommend you use this in combination with the Better Invisibility plugin.
#UPDATE: Better Invisibility may have this built in now, but this still works
Break-Invis:
  Enabled: true
  Causes:
    - 'ENTITY_ATTACK'
    - 'BLOCK_EXPLOSION'
    - 'ENTITY_EXPLOSION'

#If this is enabled, MBedwars dealers/upgrade-dealers
#Will look at the closest players
Friendly-Villagers: false

#ArenaName:PotionEffectName:amplifier
#Default amplifier is 1
#All arenas = ALL-ARENAS
Permanent-Effects:
  - 'Ruins:NIGHT_VISION'

#Message sent to players when they purchase an item
#Placeholders: {amount} {product}
Buy-Message:
  Enabled: true
  Message: '&aYou Purchased &6{product} x{amount}'

#Remove items on use
Empty-Buckets: true
Empty-Potions: true

#Sponge partials on place
Sponge-Partials: true

############### BED DESTROY EFFECTS [BETA] ###############

# NONE - None
# FIREWORK - Firework
bed-destroy-effect: 'NONE'

#-----> FIREWORK CUSTOMISATION

#RGB Color
firework-color-red: 255
firework-color-green: 255
firework-color-blue: 255

#Types:
#CREEPER - Creeper Face
#BALL - Ball
#BALL_LARGE - Large Ball
#BURST - Burst
#STAR - Star
firework-type: "STAR"

#Firework Trail
firework-trail: true

#Duration Until Firework will detonate in ticks (20 ticks = 1 sec)
firework-duration: 20