version: 2.0.1
name: MBedwarsTweaks
author: MetallicGoat
main: me.metallicgoat.tweaksaddon.MBedwarsTweaksPlugin
description: Adds some extra features to MBedwars
api-version: 1.13
depend: [MBedwars]
softdepend: [PlaceholderAPI, MBedwarsHotbarManager]