name: MBedwarsTweaks
version: 3.0.1-Dev-B
author: MetallicGoat
main: me.metallicgoat.tweaksaddon.MBedwarsTweaksPlugin
description: Adds some extra customizability to MBedwars
api-version: 1.13
depend: [ MBedwars ]
softdepend: [ PlaceholderAPI, MBedwarsHotbarManager, PrestigeAddon ]