version: 2.0.0-Pre-3
name: MBedwarsTweaks
author: MetallicGoat
main: me.metallicgoat.tweaksaddon.MBedwarsTweaksPlugin
description: Tweaks and Features for MBedwars
api-version: 1.13
depend: [MBedwars]
softdepend:
  - PlaceholderAPI