version: 1.0.0-R5
name: MBedwarsTweaks
author: MetallicGoat
main: me.metallicgoat.tweaks.MBedwarsTweaks
description: Tweaks and Features for MBedwars
api-version: 1.13
depend: [MBedwars]
softdepend: [PlaceholderAPI]
commands:
  MBedwarsTweaks:
    usage: /<command>
    permission: mbedwars-tweaks.admin